// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsALe8qmWWe1bcunKplapQtKiX6G9gXU',
    appId: '1:785638905644:web:4d3c3be8370c5e5c783e89',
    messagingSenderId: '785638905644',
    projectId: 'freezer-configurator',
    authDomain: 'freezer-configurator.firebaseapp.com',
    storageBucket: 'freezer-configurator.appspot.com',
    measurementId: 'G-JKGV4HM3LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAD8PX1IVSiBDl3zJw5tLKW-P8YV1Gms',
    appId: '1:785638905644:android:b7419d4dae726427783e89',
    messagingSenderId: '785638905644',
    projectId: 'freezer-configurator',
    storageBucket: 'freezer-configurator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xINEQh_8YfO96j3pkj_6OjynEIf_3PE',
    appId: '1:785638905644:ios:a9b59851305d9b1d783e89',
    messagingSenderId: '785638905644',
    projectId: 'freezer-configurator',
    storageBucket: 'freezer-configurator.appspot.com',
    iosClientId: '785638905644-peh5qial4elepo2vcni8v9sp8q24sun9.apps.googleusercontent.com',
    iosBundleId: 'com.example.freezerConfigurador',
  );
}
