name: freezer_configurador
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  weather_icons:
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  cloud_firestore: ^3.1.5
  json_serializable: ^6.2.0
  mqtt_client: ^9.1.0
  syncfusion_flutter_charts: ^20.2.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
